"""adicionando o username no UserForm, etc

Revision ID: 793dd7b0936d
Revises: 3e79bc3fff61
Create Date: 2024-09-05 14:40:59.375699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '793dd7b0936d'
down_revision = '3e79bc3fff61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
